name: Build and Deploy Fullstack App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install and build frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Copy build to backend/public
      - name: Copy frontend build to backend
        run: |
          rm -rf backend/public
          cp -r frontend/build backend/public

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      # (Optional) Run backend tests
      # - name: Run backend tests
      #   run: |
      #     cd backend
      #     npm test

      # (Optional) Deploy step
      # - name: Deploy backend
      #   run: |
      #     # Add your deployment script here (e.g., SSH, Render CLI, etc.)
